// Generated by CoffeeScript 1.6.1
/*
Constants
*/

var $$, k, v;

$$ = {};

$$.EOL = '\n';

$$.SUPPRESS = '==SUPPRESS==';

$$.OPTIONAL = '?';

$$.ZERO_OR_MORE = '*';

$$.ONE_OR_MORE = '+';

$$.PARSER = 'A...';

$$.REMAINDER = '...';

$$._UNRECOGNIZED_ARGS_ATTR = '_unrecognized_args';

exports.$$ = $$;

for (k in $$) {
  v = $$[k];
  exports[k] = v;
}
